namespace SubZeroFramework.Models;

/// <summary>
/// What continuous operation has taught the controller about one fan SINCE its calibration run — the
/// "gets better over time" half of the hybrid model.
/// </summary>
/// <remarks>
/// <para>
/// Only the FEED-FORWARD gain is learned online, and that restriction is the entire safety argument. Feed
/// forward is an open-loop injection: it changes what the fan does, but it does not appear in the closed-loop
/// characteristic equation, so no value of it can make the loop unstable. The worst a badly learned
/// feed-forward gain can do is over- or under-anticipate, and the PI term corrects that within seconds.
/// </para>
/// <para>
/// The feedback gains (Kp, Ki) are deliberately NOT adapted here. Adapting the terms that determine stability,
/// from data generated by the very loop they stabilise, is the classic way a self-tuning regulator drifts into
/// oscillation — and on this hardware the failure mode is a laptop that audibly surges, or worse, one that
/// under-cools while confidently reporting it has improved. Those gains change only when the user runs a
/// calibration, which is a controlled experiment with a known excitation signal.
/// </para>
/// <para>
/// Persisted per fan, so a machine keeps what it learned across restarts. Reset by a recalibration, which
/// supersedes it with a fresh measurement.
/// </para>
/// </remarks>
public sealed record AdaptiveLearningState
{
    /// <summary>
    /// Settled observations behind a <see cref="AdaptiveConfidence.Confident"/> model.
    /// </summary>
    /// <remarks>
    /// Affects only how confidence is REPORTED — the identified model is used from the moment the fit becomes
    /// separable, because by then it is already better evidence than a bootstrap guess. This threshold exists
    /// so the UI can stop nudging, not to gate anything.
    /// </remarks>
    public const int ConfidentObservationTarget = 300;

    /// <summary>
    /// How long the model must hold still before it counts as settled.
    /// </summary>
    /// <remarks>
    /// Paired with the observation count so neither alone can promote a model: a machine used the same way
    /// all week accumulates observations without ever being challenged, and a machine sitting idle overnight
    /// holds still without having learned anything.
    /// </remarks>
    public static readonly TimeSpan ConfidentStabilityWindow = TimeSpan.FromHours(6);

    /// <summary>
    /// Fractional change in the identified gain that counts as the model MOVING rather than jittering.
    /// </summary>
    /// <remarks>
    /// Recursive least squares nudges its estimate on almost every sample, so without a threshold the model
    /// would never look stable and the UI could never stop saying "still refining".
    /// </remarks>
    public const double MaterialChangeFraction = 0.02d;

    /// <summary>A fan that has learned nothing yet.</summary>
    public static AdaptiveLearningState None { get; } = new();

    /// <summary>
    /// The learned feed-forward gain, in duty points per watt, or null while nothing has been learned and the
    /// calibrated value stands.
    /// </summary>
    public double? FeedForwardDutyPerWatt { get; init; }

    /// <summary>
    /// The calibrated gain this refinement was learned AROUND, or null when nothing has been learned.
    /// </summary>
    /// <remarks>
    /// Persisted with the learned value so a resumed learner can tell "the same calibration I was refining"
    /// from "a recalibration happened while the service was down". Without it, resume cannot distinguish the
    /// two and would either discard good learning on every restart or keep learning that a fresh hot test
    /// already superseded.
    /// </remarks>
    public double? CalibratedAnchorDutyPerWatt { get; init; }

    /// <summary>How many qualified steady-state observations have been folded in.</summary>
    public int ObservationCount { get; init; }

    // ----- Identified plant, from AdaptivePlantEstimator -----
    //
    // The self-learning half: these come from fitting T ≈ a + b·P − K·duty over settled operating points, and
    // are what let a fan run Adaptive WITHOUT a hot test. Null until the observations span enough of both duty
    // and power for the fit to be separable.

    /// <summary>Identified K, in °C per duty point. Supersedes a calibrated K when present.</summary>
    public double? IdentifiedProcessGainCelsiusPerPercent { get; init; }

    /// <summary>Identified thermal resistance b, in °C per watt.</summary>
    public double? IdentifiedCelsiusPerWatt { get; init; }

    /// <summary>The fit's intercept, in °C. Persisted only so a restored fit resumes rather than restarts.</summary>
    public double? IdentifiedInterceptCelsius { get; init; }

    /// <summary>
    /// Which power measurement this fit was built from. Samples from a different source are refused.
    /// </summary>
    /// <remarks>
    /// Persisted, so a restart does not silently start folding system-power samples into a fit built from
    /// component power. See <see cref="Models.ThermalLoadSource"/>.
    /// </remarks>
    public ThermalLoadSource ThermalLoadSource { get; init; } = ThermalLoadSource.None;

    /// <summary>
    /// When the identified gain last moved by more than <see cref="MaterialChangeFraction"/>.
    /// </summary>
    /// <remarks>
    /// Distinct from <see cref="LastUpdatedAt"/>, which moves on every accepted observation. This is what the
    /// UI's "stable for {n} days" line means, and what separates <see cref="AdaptiveConfidence.Converging"/>
    /// from <see cref="AdaptiveConfidence.Confident"/>.
    /// </remarks>
    public DateTimeOffset? LastMaterialChangeAt { get; init; }

    /// <summary>
    /// How well the controller knows this fan, as of <paramref name="now"/>.
    /// </summary>
    /// <remarks>
    /// A method rather than a property because the answer depends on the clock, and a property that silently
    /// read <c>DateTimeOffset.UtcNow</c> could not be tested without one.
    /// </remarks>
    /// <param name="now">The current time.</param>
    public AdaptiveConfidence ConfidenceAt(DateTimeOffset now)
    {
        // Nothing identified: the fan is running on defaults, which is a working fan and not a failure.
        if (!HasLearned || IdentifiedProcessGainCelsiusPerPercent is null)
        {
            return AdaptiveConfidence.Learning;
        }

        if (ObservationCount < ConfidentObservationTarget)
        {
            return AdaptiveConfidence.Converging;
        }

        // Never having moved counts as stable — a model that was right from its first separable fit has
        // nothing left to settle into.
        var heldSince = LastMaterialChangeAt ?? LastUpdatedAt;
        return heldSince is null || now - heldSince >= ConfidentStabilityWindow
            ? AdaptiveConfidence.Confident
            : AdaptiveConfidence.Converging;
    }

    /// <summary>When an observation was last accepted. Moves far more often than the model itself.</summary>
    public DateTimeOffset? LastUpdatedAt { get; init; }

    /// <summary>True once anything has been learned.</summary>
    public bool HasLearned => FeedForwardDutyPerWatt is not null && ObservationCount > 0;
}
